
# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
   include:
    - devops

stages:

  - stage: BuildTest
    displayName: Build python and Test

    jobs:
      - job: pre_build_setup
        displayName: Pre Build Setup
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add conda to PATH

      - job: build_environment
        displayName: Build Environment
        dependsOn: pre_build_setup
        steps:
        - bash: conda create --yes --quiet --name fertalizer python=3.9
          displayName: Create Anaconda environment
        - script: conda env list
          displayName:  environment installation verification
        - bash: |
            source activate fertalizer
          displayName: Install Anaconda packages

      - job: run_test
        displayName: Run Test
        dependsOn: build_environment
        steps:
        - script: conda install -r ./src/webapi/requirements.txt
          displayName: 'Install dependencies'
          
        - script: python -m unittest discover -s ./src/webapi/unit_tests/ -p 'test_*.py'
          displayName: 'Run Tests'

  - stage: Deploy
    dependsOn: BuildTest
    displayName: 'Deploy Proyect'
    jobs:
      - job: Deploy
        displayName: Deploy python

        steps:
        - script: nohup python3 ./src/webapi/agroadvisory_api.py > log.txt 2>&1 &






