install.packages("remotes")
install.packages("dplyr")
install.packages("sf")
install.packages("sp")
install.packages("rgdal")
install.packages("terra")
install.packages("raster")
install.packages("rgeos")
install.packages("caret", dependencies = T)
install.packages("randomForest")
install.packages("hydroGOF")
install.packages("Metrics")
install.packages("ggplot2")
install.packages("quantregForest")
install.packages("ranger")
remotes::install_github("mikejohnson51/AOI")
remotes::install_github("mikejohnson51/climateR")
remotes::install_github("cran/spatial.tools")
