# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "pre_deploy" ]
  pull_request:
    branches: [ "pre_deploy" ]

permissions:
  contents: read

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Add conda to PATH
      run: |
        echo "##vso[task.prependpath]$CONDA/bin"
    - name: Create Anaconda environment
      run: |
        conda create --yes --quiet --name fertalizer python=3.9
    - name: Active Anaconda environment
      run: |
        eval "$(conda shell.bash hook)"
        conda activate fertalizer
    - name: Install Libgdal
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install libgdal-dev
    - name: Install Gdal
      run: |
        sudo apt-get install gdal-bin
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install GDAL==3.4.3
    - name: Install Rasterio
      run: |
        pip install -U pip
        pip install pyproject-toml
        pip install rasterio
    - name: Install dependencies
      run: |
        pip install -r ./src/webapi/requirements.txt
    - name: Run Tests
      run: |
        python -m unittest discover -s ./src/webapi/unit_tests/ -p 'test_*.py'


  MergeMaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge pre_deploy -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: pre_deploy
          target_branch: devops
          github_token: ${{ github.token }}

  Release:
    needs: Test
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1.12.0
      with:
        name: Test Release
        bodyFile: "body.md"

